# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fe233bf16cdfcb6679abafc2d349bcbcaf70eb052003daf0b4b8687c6206f60083e0701c45d2d4c62a71bd9703e9e2ab5a9e5072d249b914b2d8c6a09987091

test:
  secret_key_base: 4c564fc75972bc2ecb9712e2bfb1ecda18674f103bb5414fa663970bf521ea390a849edbe69f250bec4e3e33da5d032639dd30292dbdc9e0f0a50d0eb441b357

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
